// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkTL3zukxyGJi4h23yL7mQh3KPcQqyDAw',
    appId: '1:850628785325:web:fc55b46d07976b17b0c224',
    messagingSenderId: '850628785325',
    projectId: 'lapor-book-4f7ea',
    authDomain: 'lapor-book-4f7ea.firebaseapp.com',
    storageBucket: 'lapor-book-4f7ea.appspot.com',
    measurementId: 'G-T3FMECLTKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOdILs1vvPKFJGdAl1Mo59nNwN27ZjUIM',
    appId: '1:850628785325:android:5882760bab539729b0c224',
    messagingSenderId: '850628785325',
    projectId: 'lapor-book-4f7ea',
    storageBucket: 'lapor-book-4f7ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMGAnui2G4gSAE9xl4W-Kkj8z1JR2G2t0',
    appId: '1:850628785325:ios:3b26d3640761dc82b0c224',
    messagingSenderId: '850628785325',
    projectId: 'lapor-book-4f7ea',
    storageBucket: 'lapor-book-4f7ea.appspot.com',
    iosBundleId: 'com.example.laporFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMGAnui2G4gSAE9xl4W-Kkj8z1JR2G2t0',
    appId: '1:850628785325:ios:5f7fde2b2e57bb6bb0c224',
    messagingSenderId: '850628785325',
    projectId: 'lapor-book-4f7ea',
    storageBucket: 'lapor-book-4f7ea.appspot.com',
    iosBundleId: 'com.example.laporFirebase.RunnerTests',
  );
}
